#define ID_MAINWNDFORM                     8000

#define MAINWNDFORM_WIDTH                  349
#define MAINWNDFORM_HEIGHT                 164

#define ID_MAINFORM_BITMAP_NUM             2
#define ID_MAINFORM_BITMAP_STR             "#2"

#define ID_MAINWNDFORM_VERSION_LABEL       2001
#define ID_MAINWNDFORM_BITMAP              2002

#define ID_MAINWNDFORM_TITLE_LABEL         2003
#define ID_MAINWNDFORM_SUBTITLE_LABEL      2004

#define ID_MAINWNDFORM_NAMES_CHECKBOX      2005
#define ID_MAINWNDFORM_LONGNAMES_CHECKBOX  2006
#define ID_MAINWNDFORM_ICONS_CHECKBOX      2007
#define ID_MAINWNDFORM_TYPE_CHECKBOX       2008
#define ID_MAINWNDFORM_READONLY_CHECKBOX   2009

#define ID_MAINWNDFORM_PATH_LABEL          2010
#define ID_MAINWNDFORM_PATH_FIELD          2011

#define ID_MAINWNDFORM_START_BUTTON        4000
#define ID_MAINWNDFORM_HELP_BUTTON         4001
#define ID_MAINWNDFORM_STOP_BUTTON         4002

/* EOF */
