#define ID_DETECTORFORM                  8000

#define ID_DETECTORFORM_RECTANGLE        1000

#define ID_DETECTORFORM_WINTITLE         1001
#define ID_DETECTORFORM_WINTITLE_STRING  2001
#define ID_DETECTORFORM_NAME4LIST        1002
#define ID_DETECTORFORM_NAME4LIST_STRING 2002

#define ID_DETECTORFORM_PRESSINSERT      1003
#define ID_DETECTORFORM_PRESSSSHIFT      1004

#define ID_DETECTORFORM_ESCAPE_BUTTON    4000

/* EOF */
