// Сведения об используемом списке свойств.
#define LISTKEY LONG
#define LISTPRP LONG

typedef BYTE  (_PRPLISTISITEMEQUALSPROCEDURE) (INT, LISTKEY);  typedef _PRPLISTISITEMEQUALSPROCEDURE*  PRPLISTISITEMEQUALSPROCEDURE;
typedef BYTE  (_PRPLISTISEMPTYPROCEDURE     ) (INT);           typedef _PRPLISTISEMPTYPROCEDURE*       PRPLISTISEMPTYPROCEDURE;
typedef VOID  (_PRPLISTCREATENEWPROCEDURE   ) (INT, LISTKEY);  typedef _PRPLISTCREATENEWPROCEDURE*     PRPLISTCREATENEWPROCEDURE;
typedef VOID  (_PRPLISTDISCARDPROCEDURE     ) (INT);           typedef _PRPLISTDISCARDPROCEDURE*       PRPLISTDISCARDPROCEDURE;
typedef PVOID (_PRPLISTGETPOINTERPROCEDURE  ) (INT, LISTPRP);  typedef _PRPLISTGETPOINTERPROCEDURE*    PRPLISTGETPOINTERPROCEDURE;
typedef ULONG (_PRPLISTGETSIZERPROCEDURE    ) (LISTPRP);       typedef _PRPLISTGETSIZERPROCEDURE*      PRPLISTGETSIZERPROCEDURE;

typedef struct _PRPLISTDESC
{
  // Длина списка.
  INT Length;

  // Методы для работы со списком.
  PRPLISTISITEMEQUALSPROCEDURE IsItemEqualsTo;
  PRPLISTISEMPTYPROCEDURE      IsItemEmpty;
  PRPLISTCREATENEWPROCEDURE    CreateNewItem;
  PRPLISTDISCARDPROCEDURE      DiscardItem;
  PRPLISTGETPOINTERPROCEDURE   GetPointerForData;
  PRPLISTGETSIZERPROCEDURE     GetSizeOfData;

  // Точки в списке.
  INT Input_position;
  INT Top_position;
}
PRPLISTDESC; typedef PRPLISTDESC* PPRPLISTDESC;
